// Peta label tombol menu -> ikon ilustrasi (2026-10-04). DIBUAT dari set "ikon-dashboard" (51 ikon). Berkas: assets/menu/<nama>.png
// Tombol yang labelnya tidak ada di peta tetap memakai ikon garis bawaannya.
import type { ImageSourcePropType } from "react-native";

const PETA: Record<string, string> = {
  "Presensi Guru": "presensi-saya",
  "Presensi Pegawai": "presensi-saya",
  "Kehadiran Diri": "presensi-saya",
  "Pengenalan Wajah": "pengenalan-wajah",
  "Pengenalan Wajah Anak": "pengenalan-wajah",
  "Kehadiran Siswa": "kehadiran-siswa",
  "Persetujuan Izin": "persetujuan-izin",
  "Persetujuan Izin Guru": "persetujuan-izin-guru",
  "Presensi": "rekap-harian",
  "Rekapitulasi Kehadiran": "rekapitulasi-kehadiran",
  "Ringkasan Presensi": "ringkasan-presensi",
  "Performa Individu": "performa-individu",
  "Jam Keterlambatan": "jam-keterlambatan",
  "Lokasi Presensi": "lokasi-presensi",
  "Pengaturan Lokasi Presensi": "lokasi-presensi",
  "Aduan Masuk": "aduan-masuk",
  "Kalender Kegiatan": "kalender-kegiatan",
  "Akademik": "akademik",
  "Nilai Raport": "nilai-raport",
  "Jadwal Kerja": "jadwal-kerja",
  "Kehadiran Anak": "kehadiran-anak",
  "Akademik Anak": "akademik-anak",
  "Nilai Anak": "nilai-anak",
  "Rincian Biaya": "rincian-biaya",
  "Kirim Aduan": "kirim-aduan",
  "Kirim Aduan Sekolah": "kirim-aduan",
  "Seragam": "seragam",
  "Slip Gaji": "slip-gaji",
  "Persetujuan PSB": "persetujuan-psb",
  "Cari Siswa & Guru": "cari-siswa-guru",
  "Data Pembayaran Siswa": "data-pembayaran-siswa",
  "Keuangan": "keuangan",
  "Tagihan": "tagihan",
  "Pembayaran Masuk": "pembayaran-masuk",
  "Tunggakan": "tunggakan",
  "Rekap Keuangan": "rekap-keuangan",
  "Laporan Keuangan": "laporan-keuangan",
  "Riwayat Transaksi": "riwayat-transaksi",
  "Pemasukan": "pemasukan",
  "Pengeluaran": "pengeluaran",
  "Berita Acara": "berita-acara",
  "Berita Acara (Lihat)": "berita-acara",
  "Kelola Berita Acara": "kelola-berita-acara",
  "Statistik Konten": "statistik-konten",
  "Pengguna Diblokir": "pengguna-diblokir",
  "Buat Pengumuman": "buat-pengumuman",
  "Manajemen Pengguna": "manajemen-pengguna",
  "Kapasitas Tambahan": "kapasitas-tambahan",
  "Role & Hak Akses": "role-hak-akses",
  "Koneksi Bot WhatsApp": "koneksi-bot-wa",
  "Backup Database": "backup-database",
  "Status Sinkronisasi": "status-sinkronisasi",
  "Log Aktivitas": "log-aktivitas",
  "Kondisi VPS": "kondisi-vps",
  "Profil": "profil",
  "Tampilan Orang Tua": "profil"
};

// require() harus statis (aturan Metro bundler) - makanya daftar berkas ditulis eksplisit.
const GAMBAR: Record<string, ImageSourcePropType> = {
  "aduan-masuk": require("../../assets/menu/aduan-masuk.png"),
  "akademik": require("../../assets/menu/akademik.png"),
  "akademik-anak": require("../../assets/menu/akademik-anak.png"),
  "backup-database": require("../../assets/menu/backup-database.png"),
  "berita-acara": require("../../assets/menu/berita-acara.png"),
  "buat-pengumuman": require("../../assets/menu/buat-pengumuman.png"),
  "cari-siswa-guru": require("../../assets/menu/cari-siswa-guru.png"),
  "data-pembayaran-siswa": require("../../assets/menu/data-pembayaran-siswa.png"),
  "jadwal-kerja": require("../../assets/menu/jadwal-kerja.png"),
  "jam-keterlambatan": require("../../assets/menu/jam-keterlambatan.png"),
  "kalender-kegiatan": require("../../assets/menu/kalender-kegiatan.png"),
  "kapasitas-tambahan": require("../../assets/menu/kapasitas-tambahan.png"),
  "kehadiran-anak": require("../../assets/menu/kehadiran-anak.png"),
  "kehadiran-siswa": require("../../assets/menu/kehadiran-siswa.png"),
  "kelola-berita-acara": require("../../assets/menu/kelola-berita-acara.png"),
  "keuangan": require("../../assets/menu/keuangan.png"),
  "kirim-aduan": require("../../assets/menu/kirim-aduan.png"),
  "kondisi-vps": require("../../assets/menu/kondisi-vps.png"),
  "koneksi-bot-wa": require("../../assets/menu/koneksi-bot-wa.png"),
  "laporan-keuangan": require("../../assets/menu/laporan-keuangan.png"),
  "log-aktivitas": require("../../assets/menu/log-aktivitas.png"),
  "lokasi-presensi": require("../../assets/menu/lokasi-presensi.png"),
  "manajemen-pengguna": require("../../assets/menu/manajemen-pengguna.png"),
  "nilai-anak": require("../../assets/menu/nilai-anak.png"),
  "nilai-raport": require("../../assets/menu/nilai-raport.png"),
  "pemasukan": require("../../assets/menu/pemasukan.png"),
  "pembayaran-masuk": require("../../assets/menu/pembayaran-masuk.png"),
  "pengeluaran": require("../../assets/menu/pengeluaran.png"),
  "pengenalan-wajah": require("../../assets/menu/pengenalan-wajah.png"),
  "pengguna-diblokir": require("../../assets/menu/pengguna-diblokir.png"),
  "performa-individu": require("../../assets/menu/performa-individu.png"),
  "persetujuan-izin": require("../../assets/menu/persetujuan-izin.png"),
  "persetujuan-izin-guru": require("../../assets/menu/persetujuan-izin-guru.png"),
  "persetujuan-psb": require("../../assets/menu/persetujuan-psb.png"),
  "presensi-saya": require("../../assets/menu/presensi-saya.png"),
  "profil": require("../../assets/menu/profil.png"),
  "rekap-harian": require("../../assets/menu/rekap-harian.png"),
  "rekap-keuangan": require("../../assets/menu/rekap-keuangan.png"),
  "rekapitulasi-kehadiran": require("../../assets/menu/rekapitulasi-kehadiran.png"),
  "rincian-biaya": require("../../assets/menu/rincian-biaya.png"),
  "ringkasan-presensi": require("../../assets/menu/ringkasan-presensi.png"),
  "riwayat-transaksi": require("../../assets/menu/riwayat-transaksi.png"),
  "role-hak-akses": require("../../assets/menu/role-hak-akses.png"),
  "seragam": require("../../assets/menu/seragam.png"),
  "slip-gaji": require("../../assets/menu/slip-gaji.png"),
  "statistik-konten": require("../../assets/menu/statistik-konten.png"),
  "status-sinkronisasi": require("../../assets/menu/status-sinkronisasi.png"),
  "tagihan": require("../../assets/menu/tagihan.png"),
  "tunggakan": require("../../assets/menu/tunggakan.png"),
};

/** Gambar ikon ilustrasi utk label menu, atau null bila tidak ada. */
export function iconSourceUntukLabel(label: string): ImageSourcePropType | null {
  const nama = PETA[label];
  return nama ? (GAMBAR[nama] ?? null) : null;
}
